[package]
name = "gyroflow-toolbox"
version = "1.0.0"
authors = ["Chris Hocking <chris@latenitefilms.com>", "Adrian <adrian.eddy@gmail.com>"]
edition = "2021"

[lib]
crate-type =["cdylib"]

[dependencies]
argh = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*", features = ["preserve_order"] }
libc = "0.2"
gyroflow-core = { git = "https://github.com/gyroflow/gyroflow.git" }
log = "0.4.17"
oslog = "0.2.0"
lazy_static = "1.4"
lru = "0.10"
nalgebra = { version = "0.32", features = ["serde-serialize"] }
once_cell = "1.16.0"
metal = "0.24.0"
