[package]
name = "gyroflow"
version = "1.0.0"
edition = "2021"

[lib]
crate-type =["cdylib"]

[dependencies]
argh = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*", features = ["preserve_order"] }
libc = "0.2"
